# This is a basic workflow to help you get started with Actions

name: Run

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      version:
        description: gradle-$version-xxx.zip
        required: true
        type: string
      distribution_type:
        description: gradle-xxx-$distribution_type.zip
        required: true
        type: string
      

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Repo
        uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Download Gradle
        run: |
          wget https://services.gradle.org/distributions/gradle-${{ inputs.version }}-${{ inputs.distribution_type }}.zip

      - name: Test -> ls the ./temp dir
        run: |
          ls

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Gradle Distribution Zip Artifact
          path: *.zip
        
